zkeco-core/adms/bak/iaccess/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls.defaults import *
import models
import view
import map
import dev_comm_center

urlpatterns=patterns('mysite.iaccess',
    #(r'^media/(?P<path>.*)$', serve, {'document_root': APP_HOME+'/iaccess/media/', 'show_indexes': False}),
    (r'^DoorSetPage/$', models.models.render_doorset_page),
    (r'^EmpLevelSetPage/$', models.models.render_emplevelset_page),
    (r'^EmpLevelByLevelPage/$', models.models.render_emplevelbylevel_page),
    (r'^EmpLevelByEmpPage/$', models.models.render_emplevelbyemp_page),
    (r'^RTMonitorPage/$', models.models.render_rtmonitor_page),
    
    (r'^ReportFormPage/$', models.models.render_reportform_page),
    (r'^AllEventReportPage/$',models.models.render_alleventreport_page),
    (r'^AlarmEventReportPage/$',models.models.render_alarmeventreport_page),
    (r'^EmpLevelReportPage/$',models.models.render_emplevelreport_page),
    
    (r'^DoorMngPage/$',models.models.render_doormng_page),
    (r'^MonitorAllPage/$', models.models.render_monitorall_page),
    (r'^GetRTLog/$', models.accmonitorlog.get_redis_rtlog),
    (r'^MonitorAlarmPage/$', models.models.render_monitoralarm_page),
    (r'^ElectroMapPage/$', models.models.render_electromap_page),#电子地图
    
    (r'^GetData/$', view.get_data),#用于前端向server获取数据
    (r'^SearchACPanel/$', view.search_acpanel),#搜索控制器
    (r'^SendDoorData/$', view.send_doors_data),#开关门等
    (r'^CancelAlarm/$', view.cancel_alarm),#确认报警
    (r'^EmpLevelOp/$', view.emp_level_op),
    (r'^MCEGroupEmpOp/$', view.mcegroup_emp_op),#多卡开门人员组中人的操作（删除）
    (r'^FCOpenEmpOp/$', view.fcopen_emp_op),#删除首卡开门的人（不包括人本身）
    (r'^GetDevLog/$', dev_comm_center.get_device_monitor),
    (r'^comm_error_msg/$', dev_comm_center.comm_error_msg),
    (r'^downdata_progress/$', dev_comm_center.downdata_progress),
    (r'^ClearCmdCache/$', dev_comm_center.ClearCmdCache),
    
    (r'^ElectroMap/$', map.electro_map),#电子地图
    (r'^get_card_number/$', view.get_card_number),#实时获得未注册的卡号
    (r'^check_pwd/$', view.check_pwd)#验证旧密码是否正确
)

zkeco-core/adms/mysite/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls.defaults import *
from django.contrib.auth.views import login, logout, password_change
from settings import MEDIA_ROOT,ADDITION_FILE_ROOT,LOGIN_REDIRECT_URL,UNIT_URL
from django.template import loader, Context, RequestContext
from django.http import QueryDict, HttpResponse, HttpResponseRedirect, HttpResponseNotModified
from django.shortcuts import render_to_response
from dbapp.utils import *
from staticfiles import serve
import base
from base.log import logger
from django.core.urlresolvers import RegexURLPattern
from django.utils.translation import ugettext_lazy as _

from core.site_views import index,my_i18n,checkno

surl=UNIT_URL[1:]

def tmp_url():
    return surl+'tmp/'

urlpatterns = patterns('',
    (r'^'+surl+'api/', include('mysite.api.urls')),         #----RESTful API 接口 指向 api 目录  python-support/piston 相关 在urls最上层
    ('i18n/setlang/', my_i18n), #系统语言设置
# 几个静态文件请求
    (r'^'+surl+'file/(?P<path>.*)$', serve, {'document_root': ADDITION_FILE_ROOT, 'show_indexes': True}),
    (r'^'+tmp_url()+'(?P<path>.*)$', serve, {'document_root': tmpDir(), 'show_indexes': True}),
    (r'^'+surl+'media/(?P<path>.*)$', serve, {'document_root': MEDIA_ROOT, 'show_indexes': False}),
    (r'^media/(?P<path>.*)$', serve,  {'document_root': MEDIA_ROOT, 'show_indexes': True}),
    
    (r'^'+surl+'checkno/(?P<app_label>[^/]*)/(?P<model_name>[^/]*)/$',checkno),
    
    (r'^'+surl+'accounts/', include('mysite.authurls')),         #用户登录、登出、密码设置
    
    (r'^'+surl+'data/', include('dbapp.urls')),                         #通用数据管理
    (r'^'+surl+'iclock/', include('mysite.iclock.urls')),         #adms管理    
    (r'^'+surl+'testapp/', include('mysite.testapp.urls')),         #用于测试的应用
    (r'^'+surl+'personnel/',include('mysite.personnel.urls')),   #人事管理系统
    (r'^'+surl+'worktable/',include('mysite.worktable.urls')),   #我的工作面板
    (r'^$', index),
)

dict_urls={
    "mysite.att":url(r'^'+surl+'att/',include('mysite.att.urls'),prefix=''),#考勤系统系理
    "mysite.iaccess":url(r'^'+surl+'iaccess/',include('mysite.iaccess.urls'),prefix=''),#zkaccess门禁系统管理
    "mysite.video":url(r'^'+surl+'video/',include('mysite.video.urls'),prefix=''),#视频系统管理
    "rosetta":url(r'^rosetta/', include('rosetta.urls'),prefix='')
}

for k,v in dict_urls.items():
    if k in settings.INSTALLED_APPS:
        urlpatterns.append(v)

zkeco-core/adms/bak/iaccess/models/accantiback.py
#! /usr/bin/env python
#coding=utf-8
from django.db import models
from base.models import CachingModel
from django.utils.translation import ugettext_lazy as _
from mysite.iclock.models.model_device import Device, DEVICE_ACCESS_CONTROL_PANEL, ACPANEL_1_DOOR, ACPANEL_2_DOOR, ACPANEL_4_DOOR
from mysite.iclock.models.dev_comm_operate import sync_set_antipassback, sync_clear_antipassback
from dbapp.datautils import filterdata_by_user
from base.middleware import threadlocals

#ONEDOOR_MODE = (
#    ('one_mode', _(u'1号门读头间反潜')),#单门双向（1）
#)
#
#TWODOORS_MODE = (
#    ('one_mode', _(u'1号门读头间反潜')),#两门双向（1）
#    ('two_mode', _(u'2号门读头间反潜')),#两门双向（2）
#    ('three_mode', _(u'1,2号门间反潜')),#两门双向（4）+ 两门单向（1）
#)
#
#FOURDOORS_MODE = (
#    ('one_mode', _(u'1-2门反潜')),#四门单向（1）
#    ('two_mode', _(u'3-4门反潜')),#四门单向（2）
#    ('three_mode', _(u'1/2-3/4门反潜')),#四门单向（4）
#    ('four_mode', _(u'1-2/3门反潜')),#四门单向（5）
#    ('five_mode', _(u'1-2/3/4门反潜')),#四门单向（6）
#)

#综上，五种mode只有four_mode可能存在多个值 ，1和4，即两门双向和四门单向为4，两门单向为1

class AccAntiBack(CachingModel):
        u"""
        反潜 两门：1（1-1）、2（2-2）、(1-1，2-2)、1-2互锁 四门：1-2门反潜、3-4门反潜、（1-2 and 3-4）、1/2-3/4门反潜、1-2/3门反潜、1-2/3/4门反潜 ，单门：门自身反潜
        """
        device = models.ForeignKey(Device, verbose_name=_(u'设备'), null=True, blank=False, editable=True)
        one_mode = models.BooleanField(_(u'反潜模式1'), null=False, default=False, blank=True, editable=True)
        two_mode = models.BooleanField(_(u'反潜模式2'), null=False, default=False, blank=True, editable=True)
        three_mode = models.BooleanField(_(u'反潜模式3'), null=False, default=False, blank=True, editable=True)
        four_mode = models.BooleanField(_(u'反潜模式4'), null=False, default=False, blank=True, editable=True)
        five_mode = models.BooleanField(_(u'反潜模式5'), null=False, default=False, blank=True, editable=True)

        def limit_device_to(self, queryset):
            if self.device:
                v = AccAntiBack.objects.exclude(device=self.device).values("device")
            else:    
                v = AccAntiBack.objects.values("device")
            q = queryset.filter(device_type = DEVICE_ACCESS_CONTROL_PANEL)
            return filterdata_by_user(q.exclude(pk__in=[item["device"] for item in v]), threadlocals.get_current_user()) 
        
        def __unicode__(self):
            return _(u'设备 %s 的反潜信息') % self.device.alias
        
        def data_valid(self, sendtype):
            if not(self.one_mode or self.two_mode or self.three_mode or self.four_mode or self.five_mode):
                raise Exception(_(u'请设置设备的反潜信息'))
            
        def save(self, *args, **kwargs):
            super(AccAntiBack, self).save()#log_msg=False
            sync_set_antipassback(self.device)

        def delete(self):
            sync_clear_antipassback(self.device)
            return super(AccAntiBack,self).delete()

        def getantibackoption(self):
            anti = 0#无反潜
            if self.one_mode and self.two_mode: #双门双向
                anti = 3
            elif self.one_mode:#单门双向，双门双向，四门单向
                anti = 1
            elif self.two_mode:
                anti = 2
            elif self.three_mode:
                if self.device.accdevice.reader_count == 4:#两门双向+四门单向（均为四个读头）
                    anti = 4
                elif self.device.accdevice.reader_count == 2:#两门单向（两个读头，如C4-200）
                    anti = 1
            elif self.four_mode:
                anti = 5
            elif self.five_mode:
                anti = 6
            return anti

        def get_details(self):
            result = []
            names = self.device.accdoor_set.order_by('id').values_list('door_no','door_name')
            door_name_1 = u'%s(%s)' % (names[0][1], names[0][0])
            
            if self.device.acpanel_type == ACPANEL_1_DOOR:#单门双向
                if self.one_mode:
                    result.append(_(u"%s 读头间反潜") % door_name_1)
            
            elif self.device.acpanel_type == ACPANEL_2_DOOR and self.device.accdevice.reader_count == 4:#两门双向 含C4-200和C3400-200
                door_name_2 = u'%s(%s)' % (names[1][1], names[1][0])
                if self.one_mode:
                    result.append(_(u"%s 读头间反潜") % door_name_1)
                if self.two_mode:
                    result.append(_(u"%s 读头间反潜") % door_name_2)
                if self.three_mode:
                    result.append(_(u"%(a)s 与 %(b)s 反潜") % {"a": door_name_1, "b": door_name_2})
            
            elif self.device.acpanel_type == ACPANEL_2_DOOR and self.device.reader_count == 2:#两门单向
                door_name_2 = u'%s(%s)' % (names[1][1], names[1][0])
                if self.four_mode:
                    result.append(_(u"%(a)s 与 %(b)s 反潜") % {"a": door_name_1, "b": door_name_2})
           
            elif self.device.acpanel_type == ACPANEL_4_DOOR:
                door_name_2 = u'%s(%s)' % (names[1][1], names[1][0])
                door_name_3 = u'%s(%s)' % (names[2][1], names[2][0])
                door_name_4 = u'%s(%s)' % (names[3][1], names[3][0])
                if self.one_mode:
                    result.append(_(u"%(a)s 与 %(b)s 反潜") % {"a": door_name_1, "b": door_name_2})
                if self.two_mode:
                    result.append(_(u"%(a)s 与 %(b)s 反潜") % {"a": door_name_3, "b": door_name_4})
                if self.three_mode:
                    result.append(_(u"%(a)s与%(b)s 或 %(c)s与%(d)s 反潜") % {"a": door_name_1, "b": door_name_2, "c": door_name_3, "d": door_name_4})
                if self.four_mode:
                    result.append(_(u"%(a)s 与 %(b)s或%(c)s 反潜") % {"a": door_name_1, "b": door_name_2, "c": door_name_3})
                if self.five_mode:
                    result.append(_(u"%(a)s 与 %(b)s或%(c)s或%(d)s 反潜") % {"a":door_name_1, "b": door_name_2, "c": door_name_3, "d": door_name_4})            

            return result and u','.join(result) or _(u'暂无反潜设置信息')

        class Admin(CachingModel.Admin):
            menu_group = 'acc_doorset'
            disabled_perms = ['clear_accantiback', 'dataimport_accantiback', 'dataexport_accantiback', 'view_accantiback']
            parent_model = 'DoorSetPage'
            menu_focus = 'DoorSetPage'
            menu_index = 100023
            help_text = _(u"如果设备通讯不成功或者其他原因导致服务器无法获取设备参数，那么该设备将无法进行反潜设置。<br>已经设置过反潜功能的控制器将不会出现在设备列表中。<br>单门双向、两门双向控制器可设置读头间反潜和门之间的反潜，两门单向、四门单向控制器只能设置门之间的反潜。")
            list_display = ('device', 'antiback_details')
            newadded_column = {'antiback_details': 'get_details'}
            position = _(u'门禁系统 -> 门设置 -> 反潜设置')

        class Meta:
            app_label = 'iaccess'
            db_table = 'acc_antiback'
            verbose_name = _(u'反潜设置')
            verbose_name_plural = verbose_name

zkeco-core/adms/bak/iaccess/models/accmorecardset.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-
from django.db import models
from base.models import CachingModel
from django.utils.translation import ugettext_lazy as _
from mysite.personnel.models import AccMoreCardEmpGroup
from accdoor import AccDoor
from dbapp import data_edit
from mysite.iclock.models.dev_comm_operate import sync_set_multicard, sync_del_multicard

class AccMoreCardSet(CachingModel):
    u"""
    多卡开门组合（多卡开门组的组合）
    """ 
    door = models.ForeignKey(AccDoor, verbose_name=_(u'当前门'), null=True, blank=True, editable=True)
    comb_name = models.CharField(_(u'组合名称'), null=True, max_length=30, blank=False, unique=True)#Combination Name

    def limit_accmorecardset_to(self, queryset, user):#self 为class
        #需要过滤掉用户权限不能控制的多卡开门组合(列表datalist)
        da = user.deptadmin_set.all()
        if not user.is_superuser and da:#非超级用户如果a不为空则默认全部区域
            d_limit = [int(d.dept_id) for d in da]
            from mysite.personnel.models import Employee
            emps = Employee.objects.filter(DeptID__in=d_limit)#范围内的人
            empgroups_limit = []#所有有效的多卡开门人员组（即有效人所属的组）id
            for emp in emps:
                group = emp.morecard_group
                if group:
                    empgroups_limit.append(group)
            empgroups_all = AccMoreCardEmpGroup.objects.all()#所有多卡开 门人员组
            null_empgroups = empgroups_all.filter(employee__isnull=True)
            for ne in null_empgroups:
                empgroups_limit.append(ne)
            invisible_empgroups = [eg for eg in empgroups_all if eg not in set(empgroups_limit)]#不可见的多卡开门人员组
            #print  '-----empgroups_limit=',empgroups_limit
            #print  '-----invisible_empgroups=',invisible_empgroups
            invisible_morecardset = queryset.filter(accmorecardgroup__group__in=invisible_empgroups)#
            #print '----invisible_morecardset=',invisible_morecardset
            visible_morecardset = [ms.pk for ms in queryset if ms not in invisible_morecardset]
            #print '------visible_morecardset=',visible_morecardset
            queryset = queryset.filter(pk__in=visible_morecardset)#AccMoreCardGroup
        return queryset
    
    def __unicode__(self):
        return u"%s" % self.comb_name
    
    def data_valid(self, sendtype):
        tmp = AccMoreCardSet.objects.filter(comb_name=self.comb_name.strip())
        if tmp and tmp[0] != self:   #新增时不能重复。
            raise Exception(_(u'组合名称设置重复'))
    
    def get_groups(self):
        return ",".join([unicode(group) for group in self.accmorecardgroup_set.all()]) or _(u'暂无多卡开门组合设置信息')
    
    def save(self, *args, **kwargs):
        super(AccMoreCardSet, self).save()#log_msg=False
   
    def delete(self):
        sync_del_multicard(self)
        super(AccMoreCardSet, self).delete()
        self.door.device.check_muliticard_options(self.door)
         
    class Admin(CachingModel.Admin):
        menu_index = 1000271
        menu_focus = 'DoorSetPage'
        parent_model = 'AccDoor'
        menu_group = 'acc_doorset_'
        disabled_perms = ['clear_accmorecardset', 'dataimport_accmorecardset', 'dataexport_accmorecardset', 'view_accmorecardset', 'clear_accmorecardset']
        list_display = ('comb_name', 'morecardgroup')
        newadded_column = {'morecardgroup': 'get_groups'}
        position = _(u"门禁系统 ->门设置 -> 多卡开门设置")#组合
        help_text = _(u'最多五人同时开门，且五人至少要来自一个组。')
    
    class Meta:
        app_label = 'iaccess'
        db_table = 'acc_morecardset'
        verbose_name = _(u'多卡开门设置')#组合
        verbose_name_plural = verbose_name

class AccMoreCardGroup(CachingModel):
    u"""多卡开门组  开门组（人的组合）的组合,相当于AccMoreCardEmpGroup的组合"""
    comb = models.ForeignKey(AccMoreCardSet, verbose_name=_(u'多卡开门组合'), null=True, blank=True, editable=True)
    group = models.ForeignKey(AccMoreCardEmpGroup, verbose_name=_(u'多卡开门人员组合'), null=True, blank=True, editable=True)
    opener_number = models.IntegerField(_(u'人数'), null=True, blank=True, editable=True)

    def __unicode__(self):
        return u"%s(%s)" % (self.group, self.opener_number)

    def save(self, *args, **kwargs):
        super(AccMoreCardGroup, self).save(log_msg=False)

    class Admin(CachingModel.Admin):
        menu_focus = 'DoorSetPage'
        visible = False

    class Meta:
        app_label = 'iaccess'
        db_table = 'acc_morecardgroup'
        verbose_name = _(u'多卡开门组')
        verbose_name_plural = verbose_name
        
def DataPostBack(sender, **kwargs):
    oldObj=kwargs['oldObj']
    newObj=kwargs['newObj']
    request=sender
    if isinstance(newObj, AccMoreCardSet):
        groups = request.POST.getlist("group")
        numbers = request.POST.getlist("number")
        #groups= [u'1', u'2', u'3']
        #number= [u'2', u'', u'1'] 
        existed_objs = AccMoreCardGroup.objects.filter(comb = newObj)#此处和oldObj不同
        if existed_objs:
            #print "-------------exist"
            #print AccMoreCardGroup.objects.filter(comb = newObj)
            existed_objs.delete()
            #print AccMoreCardGroup.objects.filter(comb = newObj)
        
        for index, number in enumerate(numbers):
            if number and int(number) != 0:#0,00....
                #print groups[index]
                #print number
                
                obj = AccMoreCardGroup()
                obj.comb = newObj
                obj.group =  AccMoreCardEmpGroup.objects.filter(pk=int(groups[index]))[0]#QuerySet object => object instance
                obj.opener_number = int(number)
               
                try:
                    obj.save(force_insert=True)
                except:
                    import traceback;traceback.print_exc()
        try:
            sync_set_multicard(newObj)
        except:
            import traceback;traceback.print_exc()
        
data_edit.post_check.connect(DataPostBack)

zkeco-core/adms/bak/iaccess/templates/AccAntiBack_edit.html
{% extends "data_edit.html" %}

{% block form %}
{% if request.user|HasPerm:"iaccess.add_accantiback" or request.user|HasPerm:"iaccess.change_accantiback" %}
{% autoescape off %}
    <tr>
        <td>
            <table id="tr_antiback_mode">
                <tr>
                    {{ form.device|field_as_td_h }}
                </tr>
            
                <tr id="tr_one_mode" class="antiback_mode">
                    <th>{{ form.one_mode|field_as_no_td }}</th>
                    <td><label for="id_one_mode"></label></td>
                </tr>
                <tr id="tr_two_mode" class="antiback_mode">
                    <th>{{ form.two_mode|field_as_no_td }}</th>
                    <td><label for="id_two_mode"></label></td>
                </tr>
                <tr id="tr_three_mode" class="antiback_mode">	
                    <th>{{ form.three_mode|field_as_no_td }}</th>
                    <td><label for="id_three_mode"></label></td>
                </tr>
                <tr id="tr_four_mode" class="antiback_mode">	
                    <th>{{ form.four_mode|field_as_no_td }}</th>
                    <td><label for="id_four_mode"></label></td>
                </tr>
                <tr id="tr_five_mode" class="antiback_mode">
                    <th>{{ form.five_mode|field_as_no_td }}</th>
                    <td><label for="id_five_mode"></label></td>
                </tr>
                {% if form.non_field_errors %}
                    <tr><td>{{ form.non_field_errors }}</td></tr>
                {% endif %}
            </table>
        </td>
    </tr>
{% endautoescape %}
{% endif %}<!--add/change_accantiback-->
{% endblock %}

{% block addjs %}
    {% if request.user|HasPerm:"iaccess.add_accantiback" or request.user|HasPerm:"iaccess.change_accantiback" %}
    var after_init = function()
    {		
        //select option分层级ie不兼容问题,以及ie6不支持option的disabled的问题
        if($.browser.msie) 
        {
            $("#id_device .level_1").each(function(){
                $(this).text("         "+$(this).text());
            });

            $("#id_device .level_0").each(function(){
                $(this).attr("style", "color:#999999");
            });
			$("#tr_antiback_mode").find("th").css({"width": "130px"});
            $("#id_device").change(function(){
                var options = $("#id_device option");   
                var len = options.length; 
                for(var i = 0; i < len; i++)
                {   
                    if(options[i].disabled && options[i].selected)
                    {  
                        options[0].selected = "selected";   
                        break;   
                    }
                }   
            });
        }   
    } 

    function before_submit()
    {
        if($("#id_device").attr("disabled") == true)//编辑时不做处理，且不执行下面的判断
        {
            $("#id_device").attr("disabled", false);
             return true;
        }
        return true;   
    }
    
    if( $("#id_device").val() != "")//编辑时
    {
        $("#id_device").attr("disabled", true);
    }
    else//新增时
    {
        $("#tr_antiback_mode tr:gt(0)").hide();
    }
    
    //用户没有选择控制器前先检查控制器是两门还是四门以及读头数量。同样适应与编辑时不允许用户更改控制器的情况
    var init_value = $("#id_device").val();

    function check_device(device_id)
    {
        geturl = "/{{ request.surl }}iaccess/GetData/?func=machine_args&device_id=" + device_id;     
        $.ajax({
            type: "GET",
            url: geturl,
            dataType: "json",
            async: false,
            success: function(data){
                var doorcount = data.door_count;
                var readercount = data.reader_count;
                var names = data.doors_name;
                var door_name_1 = names[0][1] + "(" + names[0][0] + ")";
                var door_name_2 = "";
                var door_name_3 = "";
                var door_name_4 = "";
                
                if(doorcount == 0)//尚未连接过
                {
                    $("tr[id^='tr_']").hide()
                    alert(gettext("当前选择设备的扩展参数获取失败，无法对该设备进行反潜设置！"));
                }
                else if(doorcount == 4)//四门单向
                {
                    door_name_2 = names[1][1] + "(" + names[1][0] + ")";
                    door_name_3 = names[2][1] + "(" + names[2][0] + ")";
                    door_name_4 = names[3][1] + "(" + names[3][0] + ")";

                    $("#tr_antiback_mode tr:gt(0)").show();
                    $("#tr_one_mode td label").text(gettext("门:")+door_name_1+" "+gettext("与")+" "+door_name_2+gettext("反潜"));
                    $("#tr_two_mode td label").text(gettext("门:")+door_name_3+" "+gettext("与")+" "+door_name_4+gettext("反潜"));
                    $("#tr_three_mode td label").text(gettext("门:")+door_name_1+gettext("或")+door_name_2+" "+gettext("与")+" "+door_name_3+gettext("或")+door_name_4+gettext("反潜"));
                    $("#tr_four_mode td label").text(gettext("门:")+door_name_1+" "+gettext("与")+" "+door_name_3+gettext("或")+door_name_4+gettext("反潜"));    
                    $("#tr_five_mode td label").text(gettext("门:")+door_name_1+" "+gettext("与")+" "+door_name_2+gettext("或")+door_name_3+gettext("或")+door_name_4+gettext("反潜"));  
                }
                else if(doorcount == 1)//单门双向
                {
                    $("#tr_antiback_mode tr:gt(0)").show();
                    $("#tr_two_mode").hide();
                    $("#tr_three_mode").hide();
                    $("#tr_four_mode").hide();
                    $("#tr_five_mode").hide();

                    $("#tr_one_mode th label").text(gettext("门:")+door_name_1+gettext("读头间反潜"));
                }
                else if(doorcount == 2 && readercount == 4)//双门双向
                {
                    door_name_2 = names[1][1] + "(" + names[1][0] + ")";
                    $("#tr_antiback_mode tr:gt(0)").show();
                    $("#tr_four_mode").hide();
                    $("#tr_five_mode").hide();
                      
                    $("#tr_one_mode td label").text(gettext("门:")+door_name_1+gettext("读头间反潜"));
                    $("#tr_two_mode td label").text(gettext("门:")+door_name_2+gettext("读头间反潜"));
                    $("#tr_three_mode td label").text(gettext("门:")+door_name_1+" "+gettext("与")+" "+door_name_2+gettext("反潜"));
                }
                else if(doorcount == 2 && readercount == 2)//双门单向
                {
                    door_name_2 = names[1][1] + "(" + names[1][0] + ")";
                    $("#tr_antiback_mode tr:gt(0)").show();
                    $("#tr_one_mode").hide()
                    $("#tr_two_mode").hide();
                    $("#tr_four_mode").hide();
                    $("#tr_five_mode").hide();
                      
                    $("#tr_three_mode td label").text(gettext("门:")+door_name_1+" "+gettext("与")+" "+door_name_2+gettext("反潜"));             
                }
                else
                {
                    alert(gettext("读取到错误的设备信息，请重试！"));
                }
            },
            error:function (XMLHttpRequest, textStatus, errorThrown) 
            {
                //alert(textStatus+" "+errorThrown);
                alert(gettext("服务器处理数据失败，请重试！错误码：-602"));
                return false;
            }
        });
    }

    if(init_value)//编辑时
    {
        check_device(init_value);
    }

    //用于用户新增数据时
    $("#id_device").change(function(){
        var device_id = $(this).find("option:selected").val();
        if(device_id)
        {
            check_device(device_id);
        }
    });

    $("#id_one_mode").click(function(){
         if($(this).attr("checked"))
         {
            $("#id_three_mode").removeAttr("checked");
            $("#id_four_mode").removeAttr("checked");
            $("#id_five_mode").removeAttr("checked");
         }
    });
    $("#id_two_mode").click(function(){
         if($(this).attr("checked"))
         {
            $("#id_three_mode").removeAttr("checked");
            $("#id_four_mode").removeAttr("checked");
            $("#id_five_mode").removeAttr("checked");
         }
    });
    $("#id_three_mode").click(function(){
         if($(this).attr("checked"))
         {
            $("#id_one_mode").removeAttr("checked");
            $("#id_two_mode").removeAttr("checked");
            $("#id_four_mode").removeAttr("checked");
            $("#id_five_mode").removeAttr("checked");
         }
    });
    $("#id_four_mode").click(function(){
         if($(this).attr("checked"))
         {
            $("#id_one_mode").removeAttr("checked");
            $("#id_two_mode").removeAttr("checked");
            $("#id_three_mode").removeAttr("checked");
            $("#id_five_mode").removeAttr("checked");
         }
    });
    $("#id_five_mode").click(function(){
         if($(this).attr("checked"))
         {
            $("#id_one_mode").removeAttr("checked");
            $("#id_two_mode").removeAttr("checked");
            $("#id_three_mode").removeAttr("checked");
            $("#id_four_mode").removeAttr("checked");
         }
    });
    
    {% else %}     
        alert(gettext("对不起，您没有访问该页面的权限，不能浏览更多信息！"));
        window.location.href = "/{{ request.surl }}accounts/login/";
    {% endif %}<!--add/change_accantiback-->

{% endblock %}