zkeco-core/adms/mysite/personnel/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls.defaults import *
from models.model_empchange  import get_empchange_postion
from views import get_dept_tree_data
from models.empwidget import get_widget_for_select_emp
import report
import views
urlpatterns=patterns('mysite.personnel',
    (r'^getempchange_value/(?P<userid>[^/]*)/(?P<num>[^/]*)/$',get_empchange_postion),
    (r'^get_dept_tree_data$', get_dept_tree_data),
    (r'^GenerateEmpFlow/$', report.GenerateEmpFlow),
    (r'^GenerateDeptRoster/$', report.GenerateDeptRoster),
    (r'^GenerateEmpEducation/$', report.GenerateEmpEducation),
    (r'^GenerateEmpCardList/$', report.GenerateEmpCardList),
    (r'^choice_widget_for_select_emp/$',get_widget_for_select_emp),
    (r'^getchange/$', views.getchange),
    (r'^getmodeldata/(?P<app_lable>[^/]*)/(?P<model_name>[^/]*)/$',views.funGetModelData),
)
 

zkeco-core/adms/mysite/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls.defaults import *
from django.contrib.auth.views import login, logout, password_change
from settings import MEDIA_ROOT,ADDITION_FILE_ROOT,LOGIN_REDIRECT_URL,UNIT_URL
from django.template import loader, Context, RequestContext
from django.http import QueryDict, HttpResponse, HttpResponseRedirect, HttpResponseNotModified
from django.shortcuts import render_to_response
from dbapp.utils import *
from staticfiles import serve
import base
from base.log import logger
from django.core.urlresolvers import RegexURLPattern
from django.utils.translation import ugettext_lazy as _

from core.site_views import index,my_i18n,checkno

surl=UNIT_URL[1:]

def tmp_url():
    return surl+'tmp/'

urlpatterns = patterns('',
    (r'^'+surl+'api/', include('mysite.api.urls')),         #----RESTful API 接口 指向 api 目录  python-support/piston 相关 在urls最上层
    ('i18n/setlang/', my_i18n), #系统语言设置
# 几个静态文件请求
    (r'^'+surl+'file/(?P<path>.*)$', serve, {'document_root': ADDITION_FILE_ROOT, 'show_indexes': True}),
    (r'^'+tmp_url()+'(?P<path>.*)$', serve, {'document_root': tmpDir(), 'show_indexes': True}),
    (r'^'+surl+'media/(?P<path>.*)$', serve, {'document_root': MEDIA_ROOT, 'show_indexes': False}),
    (r'^media/(?P<path>.*)$', serve,  {'document_root': MEDIA_ROOT, 'show_indexes': True}),
    
    (r'^'+surl+'checkno/(?P<app_label>[^/]*)/(?P<model_name>[^/]*)/$',checkno),
    
    (r'^'+surl+'accounts/', include('mysite.authurls')),         #用户登录、登出、密码设置
    
    (r'^'+surl+'data/', include('dbapp.urls')),                         #通用数据管理
    (r'^'+surl+'iclock/', include('mysite.iclock.urls')),         #adms管理    
    (r'^'+surl+'testapp/', include('mysite.testapp.urls')),         #用于测试的应用
    (r'^'+surl+'personnel/',include('mysite.personnel.urls')),   #人事管理系统
    (r'^'+surl+'worktable/',include('mysite.worktable.urls')),   #我的工作面板
    (r'^$', index),
)

dict_urls={
    "mysite.att":url(r'^'+surl+'att/',include('mysite.att.urls'),prefix=''),#考勤系统系理
    "mysite.iaccess":url(r'^'+surl+'iaccess/',include('mysite.iaccess.urls'),prefix=''),#zkaccess门禁系统管理
    "mysite.video":url(r'^'+surl+'video/',include('mysite.video.urls'),prefix=''),#视频系统管理
    "rosetta":url(r'^rosetta/', include('rosetta.urls'),prefix='')
}

for k,v in dict_urls.items():
    if k in settings.INSTALLED_APPS:
        urlpatterns.append(v)

zkeco-core/adms/mysite/personnel/models/model_empchange.py
#! /usr/bin/env python
#coding=utf-8

from django.db import models
from base.models import CachingModel
from base.operation import Operation,ModelOperation
from django.utils.translation import ugettext_lazy as _
from model_leave import YESORNO
from django.contrib.contenttypes.models import ContentType
from dbapp import data_edit
from base.base_code import BaseCode,base_code_by

from mysite.personnel.models import Department
from mysite.personnel.models.model_emp import HIRETYPE,EMPTYPE
from mysite.personnel.models.model_emp import Employee,EmpForeignKey,EmpMultForeignKey,EmpPoPForeignKey,EmpPoPMultForeignKey
from mysite.personnel.models.model_area import Area,AreaManyToManyField
from dbapp.utils import getJSResponse
from django.utils.encoding import smart_str
from django.utils.simplejson  import dumps
from django.db.models import Q
from base.base_code import BaseCode,base_code_by
from mysite.iclock.models.dev_comm_operate import *
import datetime
from django.conf import settings


APPROVAL=(
        (1,_(u'申请')),
        (2,_(u'已批')),
)
POSTION=(
        (1,_(u'部门')),
        (2,_(u'职务')),
        (3,_(u'雇用类型')),
        (4,_(u'区域')),
)
def to_json(obj):
    #print obj
    ret=[]
    for t in obj:
        x=[]
        x.append(t[0])
        x.append(u"%s"%t[1])
        ret.append(list(x))
    return ret
def get_empchange_postion(request,userid,num):
    from model_emp import Employee
    num=int(num)
    userid=int(userid)
    user=Employee.objects.filter(id=userid)    
    qs={}
    try:
        if user:
            qs['old']=get_user_postion(user[0],num)
            qs['new']=to_json(get_empchange_postion_list(num))
        #print qs
    except:
        import traceback;traceback.print_exc()
    return getJSResponse(smart_str(dumps(qs)))

def get_user_postion(user,num):
    
    if num==1:  #部门
        return user.DeptID.id
    elif num==2:#职务
        return user.Title
    elif num==3:#雇用类型
        return user.emptype
    else:       #区域
        tt=user.attarea.select_related().values_list('pk')
        ret=[]
        for i in tt:
            ret.append(i[0])               
        return ret
    
def get_empchange_postion_list(num):
    
    if num==1:  #部门
        return Department.objects.all().values_list('id','name')
    elif num==2:#职务
        return BaseCode.objects.filter(content='TITLE').values_list('id','display')
    elif num==3:#雇用类型
    
        return EMPTYPE
    else:               #区域
        return Area.objects.all().values_list('id','areaname')
            
        
POSTIONMODEL=[
        Department.objects.all(),
        base_code_by('TITLE'),
        EMPTYPE,
        Area.objects.all()
        ]

def show_visible():
    if settings.APP_CONFIG.language.language!='zh-cn':
        return False
    else:
        if "mysite.att" in settings.INSTALLED_APPS:
            return True
        else:
            return False

from model_emp import EmpForeignKey
class EmpChange(CachingModel):
        '''调动表'''
        changeno=models.AutoField(verbose_name=_(u'调动单号'),db_column='changeno',primary_key=True,editable=False)
        UserID=EmpPoPForeignKey(verbose_name=_(u"人员"),editable=True)
        changedate=models.DateTimeField(verbose_name=_(u'调动时间'),null=True,blank=True,editable=True,default=datetime.datetime.now())
        changepostion=models.IntegerField(verbose_name=_(u'调动栏位'),choices=POSTION,editable=True,null=True,blank=True,)        
        oldvalue=models.CharField(verbose_name=_(u'调动前'),max_length=100,editable=True,null=True,blank=True)
        newvalue=models.CharField(verbose_name=_(u'调动后'),max_length=100,editable=True,null=True,blank=True)
        changereason=models.CharField(max_length=200,verbose_name=_(u'调动原因'),null=True,blank=True,editable=True)
        isvalid=models.BooleanField(verbose_name=_(u'是否生效'),choices=YESORNO,editable=True,default=0)
        approvalstatus=models.IntegerField(verbose_name=_(u'审核状态'),choices=APPROVAL,editable=False,default=2)
        remark=models.CharField(verbose_name=_(u'备注'),editable=True,null=True,blank=True,max_length=200)
        def __unicode__(self):
                       return self.UserID.PIN+(self.UserID.EName and " %s"%self.UserID.EName or "")

        def save(self):
            #ContentType.objects.get_for_model(obj)
            #print "self.changepostion:%s"%self.changepostion
            try:
                if self.changepostion and int(self.changepostion) in [1,2,3,4]:  #同步人员信息表,并原还页面上有可能修改原始数据
                    cmp = [_(u'请选择调整后的部门'),_(u'请选择调整后的职务'),_(u'请选择调整后的雇佣类型'),_(u'请选择调整后的区域')]
                    if not self.newvalue:
                        raise Exception(cmp[int(self.changepostion)-1])
                    where={}
                    if self.changepostion==1:
                        self.oldvalue=self.UserID.DeptID.pk
                        where['id__exact']=int(self.newvalue)
                        self.UserID.DeptID=Department.objects.filter(Q(**where))[0]
                        
                    elif self.changepostion==2:
                        self.oldvalue=self.UserID.Title
                        try:
                            where['id__exact']=int(self.newvalue)
                            t=BaseCode.objects.filter(Q(**where))
                            if t:
                                self.UserID.Title=t[0]
                            else:
                                self.UserID.Title=""
                        except:
                            self.UserID.Title=self.newvalue
                        
                    else:
                        self.oldvalue=self.UserID.emptype
                        self.UserID.emptype=int(self.newvalue)
                        
                    self.UserID.save()
                
                super(EmpChange,self).save()
            except Exception, e:
                import traceback; traceback.print_exc();
                raise e
                return self
        class _delete(Operation):
            visible=False
            def action(self):
                pass
        class OpAvailable(Operation):
            help_text=_(u'立即生效')
            verbose_name=_(u'立即生效')
            visible=False
            def action(self):
                self.object.approvalstatus=2
                self.object.isvalid=1
                self.object.save()
            
        def get_value(self,type=1):
            #print "type:%s"%type
            from mysite.personnel.models import Department,Area
            if type==1:
                data=self.oldvalue
            else:
                data=self.newvalue
            if not data:
                return ""    
            if self.changepostion==1:
                return u"%s"%Department.objects.get(pk=int(data))
            elif self.changepostion==2:
                where={}
                where['id__exact']=int(data)
                t=BaseCode.objects.filter(Q(**where))
                return u"%s"%t[0]
            elif self.changepostion==3:
                return u"%s"%EMPTYPE[int(data)-1][1]    
            else:
                area=Area.objects.filter(pk__in=data.split(","))
                return u",".join([u"%s"%a.areaname for a in area])
            
        def get_value(self,type):
            from mysite.personnel.models import Department,Area    
            if type==1:
                data=self.oldvalue
            else:
                data=self.newvalue
            #print "emp data:%s"%data
            if not data:
                return ""    
            if self.changepostion==1:
                return u"%s"%Department.objects.get(pk=int(data))
            elif self.changepostion==2:
#                where={}
#                where['value__exact']=int(data)
#                where['display__exact']='TITLE'
#                t=BaseCode.objects.filter(Q(**where))
                t=base_code_by('TITLE')
                
                for i,v in t:
                    if int(i)==int(data):
                        return v
                return ""
#                if t:
#                    return u"%s"%t[0]
#                else:
#                    return ""
            elif self.changepostion==3:
                return u"%s"%EMPTYPE[int(data)-1][1]    
            else:
                area=Area.objects.filter(pk__in=data.split(","))
                return u",".join([u"%s"%a.areaname for a in area])
                
        def get_oldvalue(self):            
            return self.get_value(1)      

        def get_newvalue(self):
            return self.get_value(2)
        
        class Admin(CachingModel.Admin):
                from django.forms import Select
                sort_fields=["changeno","UserID.PIN","changedate"]
                app_menu="personnel"
                visible = show_visible()#暂只有考勤使用
                list_filter=('UserID','approvalstatus','isvalid')
                query_fields=['UserID__PIN','UserID__EName','changepostion','changereason']
                list_display=['UserID.PIN','UserID.EName','changepostion','oldvalue','newvalue','changedate','changereason','remark']
                newadded_column = {'oldvalue' : 'get_oldvalue','newvalue' : 'get_newvalue'}
                menu_index=3
                help_text=_(u"区域的调整：将会把该人员所属原区域内的设备清除掉该人员，并自动下发到新区域内的所有设备中")
                #default_widgets={'oldvalue':Select,'newvalue':Select}
                disabled_perms=['dataimport_empchange','opavailable_empchange','delete_empchange']
        class Meta:
                app_label='personnel'
                verbose_name=_(u'人员调动')
                verbose_name_plural=verbose_name
        
#在表单生成前加入自定义字段 或操作
def detail_resplonse(sender, **kargs):

zkeco-core/adms/mysite/personnel/views.py
# Create your views here.
#coding=utf-8
from models.model_dept import Department
from dbapp.utils import getJSResponse
from django.utils.encoding import smart_str
from base.model_utils import GetModel
from django.db.models import Q
from django.utils.simplejson  import dumps 
import datetime

def get_dept_tree_data(request):
    selected=request.REQUEST.getlist("K")
    selected=[int(item) for item in selected]
    level=request.REQUEST.get("LEVEL","1")
    root=request.REQUEST.get("root","1")
    try:
        root=int(root)
    except:
        root=None
        if level=='1': level=2
    from models import depttree
    html=depttree.DeptTree(Department.objects.all()).html_jtree(selected,root_id=root, next_level=int(level))
    return getJSResponse(html)

def getchange(request):
    from mysite.personnel.models import Employee    
    id=request.GET.get("k")
    u=Employee.objects.get(pk=id)
    data={}
    if u:
        data['dept']=int(u.DeptID_id)
        data['title']=u.Title and str(u.Title) or 0
        data['hiretype']=u.emptype and str(u.emptype) or 1
        data['attarea']=[int(i.pk) for i in u.attarea.all()]
    return getJSResponse(smart_str(data))

def funGetModelData(request,app_lable,model_name):
        from mysite.personnel.models.model_emp  import format_pin
        model=GetModel(app_lable,model_name)
        fields=request.REQUEST.get("fields","")
        userid=request.REQUEST.get("userid","")
        orgdept=request.REQUEST.get("orgdept","")
        para=dict(request.REQUEST)
        where={}
        for p in para:
                
                if p.find("__")>0:
                    t=p.split("__")
                    
                        
                    if p.find("__range")>0:
                        where[str(p)]=eval(para[p])
                    elif p.find("__in")>0:
                        where[str(p)]=para[p].split(",")
                    else:
                        where[str(p)]=para[p].decode("utf-8")                
                    
        #print where
        #print model
        if fields:
                fields=fields.split(",")
        if model:
                if userid:
                        data=model.objects.filter(id__in=userid)
                else:
                        data=model.objects.all()
                if where:
                        data=model.objects.filter(Q(**where))
                #print data
                if fields:
                        data=data.values_list(*fields)
                #print data
                xdata=[]
                i=0 
                while i<len(data):
                        tmpdata=data[i]
                        j=0
                        ndata=[]
                        while j<len(tmpdata):
                                #print type(tmpdata[j])
                                if type(tmpdata[j])==datetime.time:
                                        #print "1"
                                        ndata.append(tmpdata[j].strftime("%H:%M:%S"))
                                elif type(tmpdata[j])==datetime.date:
                                        ndata.append(tmpdata[j].strftime("%Y-%m-%d"))
                                else:
                                        ndata.append(tmpdata[j])
                                j+=1
                        xdata.append(ndata)
                        i+=1
                #print xdata
                if orgdept:
                    xdata=processdept(xdata)
                return getJSResponse(smart_str(dumps(xdata)))
        else:
                return NoFound404Response(request)
def processdept(xdata):
    first=0
    ret=[]    
    tmp=[]
    for d in xdata:
        if d[2]==None or d[2]==d[0]:
            ret.append(d)
        else:
            tmp.append(d)
    cur=0
    while cur<len(ret):
        xtmp=[]
        for i in tmp:
            if i[2]==ret[cur][0]:
                ret.append(i)
            else:
                xtmp.append(i)
        tmp=xtmp
        cur+=1
   # print ret
    return ret

zkeco-core/adms/mysite/personnel/templates/Department_edit.html
{% extends "data_edit.html" %}
{% load i18n %}

{% block form %}
{% autoescape off %} 
<tr><td>

  <table width="100%" border="0" cellspacing="0" cellpadding="3">
    <tr>
        {{form.name|field_as_td_h}}
      <td  >{{form.name.errors }}</td>
      
    </tr>
    <tr>
        {{form.code|field_as_td_h}}
	 
      <td  >{{form.code.errors }}<div  class="floatL Link_blue1 lineH22"><a href="javascript:void(0)" onclick="wgCheckNo('code','div_id_code',this,'{{dbapp_url}}','personnel','Department')">{%trans '验证'%}</a></div><div id='div_id_code'  class="floatL color_orange lineH22"></div></td>
     
    </tr>
    <tr>
	 {{form.parent|field_as_td_h}}
      <td  >{{form.parent.errors }}</td>
      
    </tr>


   {% for i,k in form.errors.items %}
   {{i}}{{k}}
   {% endfor %}
   

  </table>
</td></tr>

{% endautoescape %}
{% endblock %}

zkeco-core/adms/mysite/personnel/templates/Department_list.html
{% extends "data_list.html" %}
{% block headjs%}
{% endblock %}
{% load i18n %}
{% block addjs %}
    $(function(){
    	
    	$("#id_op_for_tab").append("<ul><li id='id_show_dept' alt='0'><a href='javascript:void(0)' class='action_showDeptTree'>"+gettext('显示部门树')+"</a></li></ul>");
        $("#dept_tree").treeview();
        $(".div_inline").append($("#id_show_dept_data"));
		$(".div_inline").addClass("showDeptTree");
        $("#id_op_for_tab").find("ul").eq(0).hide();
		$("#id_show_dept_data").show();
		$("#id_show_dept_data").find("#id_show_dept_tree").css({height:$(".dt_bdiv").height()+42});
        $("#id_show_dept").click(function(){
        	if($(this).attr("alt")=="0")
            {
            	//$(".div_inline").removeClass("cba");
            	$(".div_inline").addClass("showDeptTree");
            	$(this).attr("alt","1");
                $("#id_show_dept").html("<a href='javascript:void(0)' class='action_hideDeptTree'>"+gettext('隐藏部门树')+"</a>");
               
                $("#id_show_dept_data").removeClass("displayN");
                $("#id_show_dept_data").show()
                
            }
            else
            {
            	$("#id_show_dept").html("<a href='javascript:void(0)' class='action_showDeptTree'>"+gettext('显示部门树')+"</a>");
                $("#id_show_dept_data").addClass("displayN");
            	$("#id_show_dept_data").hide();
                $(".div_inline").removeClass("showDeptTree");
            	//$(".div_inline").addClass("cba");
                $(this).attr("alt","0");
            }
            
        });
        $("#id_spn_refresh").click(function(){
            $.ajax({ 
            	type: "POST",
            	url:"{{dbapp_url}}personnel/Department/choice_data_widget?depttree=True",
            	dataType:"html",
            	success:function(json){ 
                    data=json
                    $("#dept_tree").html(data).hide();
                    $("#dept_tree").treeview(); 
                    $("#dept_tree").show();          		
            	}
            });	
            
        });
    })
    

{% endblock %}
{% load personnel_tags %}

{% block addition_content %} <div id='id_show_dept_data' class="div_box floatR" style="width:25%; margin-right:5px !important; margin-left:0px !important; display:none;"><h1 align="right">&nbsp;<a id="id_spn_refresh" href="javascript:void(0)">{% trans '刷新' %}</a ></h1><div id="id_show_dept_tree" style="overflow: auto;  width:100%"><!--height: 323px;height: 302px\9;_height: 326px;--><ul id="dept_tree" >{% dept_tree %}</ul></div><div class='clear'></div></div> {% endblock %}

zkeco-core/adms/mysite/personnel/templates/EmpChange_edit.html
{% extends "data_edit.html" %}
{% load i18n %}
{% block addjs %}
$(function(){
	var $div=$("form#id_edit_form")
	var load=true
	var newdept=""
	var newtitle=""
	var newhiretype=""
	var newattarea=""
	var blnAdd=false
    $div.find(".tr_postion").each(function(){
    	$(this).addClass("displayN");
    });
	if($div.find("#id_newvalue").val()=="")//新增
	{
	  $div.find("#id_pop_emp").change(function(){
			$.ajax({
				url:"/{{request.surl}}personnel/getchange/?k="+$(this).attr("data"),
				dataType:"json",
				type:"GET",
				success:function(data){
					newdept=data.dept
					newtitle=data.title
					newhiretype=data.hiretype
					newattarea=data.attarea
					for(i in data)
					{
						switch(i)
						{
							case "dept":	
								$div.find(".tr_dept").find("p").removeClass("s");
								$div.find(".tr_dept").find("li").each(function(){
									if($(this).attr("id")==newdept)
									{
										$(this).find("p:first").addClass("s");
										$(".tr_dept").find("input:first").val($(this).find("p:first").text())
										return false;
									}
								});
								break;
							case "title":
								
								$div.find("#id_oldtitle").val(newtitle);
								break;
							case "hiretype":
								
								$div.find("#id_oldhiretype").val(newhiretype);
								break;
							case "attarea":
								$div.find(".tr_area").find("p").removeClass("s");
								for(var i=0;i<newattarea.length;i++)
								{
									$div.find(".tr_area").find("li").each(function(){
										if($(this).attr("id")==newattarea[i])
										{
											$(this).find("p:first").addClass("s");
											return false;
										}
									})
								}
								break;
							default:
								break;				
						}
					}
					
				}
				
			})
	  });
	}
	
    $div.find("#div_id_chk input[type='checkbox']").click(function(){
		
    	if(load || $(this).attr("checked"))        
        {
			//alert("123")
        	$div.find(".tr_"+$(this).attr("name").substr(3)).removeClass("displayN");            
        }
        else
        {
			//alert("456")
        	$div.find(".tr_"+$(this).attr("name").substr(3)).addClass("displayN");
        }
		var bln=false
		$div.find("#div_id_chk input[type='checkbox']").each(function(){
			if($(this).attr("checked"))
			{
				bln=true;
				return false;
			}					
		});
		if (load || bln)
		{
			$div.find(".tr_message").addClass("displayN");
		}
		else
		{
			$div.find(".tr_message").removeClass("displayN");			
		}
		load=false
		
		if(blnAdd)
		{

			
		}
    });
    if($div.find("#id_newvalue").val()!="")//编辑
    {
    	
		$div.find("#id_chkdept").parent().addClass("displayN");
		$div.find("#id_chktitle").parent().addClass("displayN");
		$div.find("#id_chkhiretype").parent().addClass("displayN");
		$div.find("#id_chkarea").parent().addClass("displayN");
		var pos=parseInt($div.find("#id_changepostion").val());
        
        if (pos==1)//部门
        {
        	$div.find("#id_chkdept").parent().removeClass("displayN");
			
            $div.find("#id_chkdept").click();
			
            $div.find("#id_olddept").val($div.find("#id_oldvalue").val());
            $div.find("#id_newdept").val($div.find("#id_newvalue").val());
        }
        if (pos==2)//职务
        {	
			
        	$div.find("#id_chktitle").parent().removeClass("displayN");
			
            $div.find("#id_chktitle").click();
			
            $div.find("#id_oldtitle").val($div.find("#id_oldvalue").val());
            $div.find("#id_newtitle").val($div.find("#id_newvalue").val());
        }
        if (pos==3)//雇用类型
        {
			
        	$div.find("#id_chkhiretype").parent().removeClass("displayN");
			
            $div.find("#id_chkhiretype").click();
			
            $div.find("#id_oldhiretype").val($div.find("#id_oldvalue").val());
            $div.find("#id_newhiretype").val($div.find("#id_newvalue").val());
           
        }
        if (pos==4)//区域
        {
			
        	$div.find("#id_chkarea").parent().removeClass("displayN");
	
            $div.find("#id_chkarea").click();
			

            var s="";
            s=$div.find("#id_newvalue").val();
            var area=[];
            
            if (s.indexOf(",")>0)
	            area=s.split(",");
            else
            	area.push(s);
            //alert(area.toString());
            for(var i=0;i<area.length;i++)
            {
                $("form#id_edit_form").find("#id_newarea li").each(function(){
                   if($(this).attr("id")==area[i])
                    {
						$(this).click();
    	                //$($(this).children()[0]).attr("checked","checked");
        	            return false;
	                }
                })
            }
            var os="";
            os=$div.find("#id_oldvalue").val();
            var oldarea=[];
            
            if (os.indexOf(",")>0)
	            oldarea=os.split(",");
            else
            	oldarea.push(os);
            
            for(var i=0;i<oldarea.length;i++)
            {
                $("form#id_edit_form").find("#id_oldarea li").each(function(){
                   if($(this).attr("id")==oldarea[i])
                    {
						$(this).click();
    	                //$($(this).children()[0]).attr("checked","checked");
        	            return false;
	                }
                })
            }
        }
        load=false
    }
});
function before_submit()
{
	var hascheck=false;
	$("#div_id_chk").find("input[type='checkbox']").each(function(){
		if($(this).attr("checked"))
		{
			hascheck=true;
			return false;
		}
	});
	if(!hascheck)
	{
		alert(gettext("请选择一个调动栏位"));
		return false;
	}
	return true;
}
{% endblock %}
{% block form %}
{% autoescape off %} 
<tr><td>
<div>
<table class="tbl_EmpChange"  cellpadding='2' cellspacing='0'>
	<tr>{{form.non_field_errors}}</tr>
	<tr>{{form.UserID|field_as_td_h}}</tr>
    <tr>{{form.changedate|field_as_td_h}}</tr>
    <tr>{{form.changereason|field_as_td_h}}</tr>
    <!-- <tr>{{form.isvalid|field_as_td_h}}</tr> -->

    <tr>{{form.remark|field_as_td_h}}</tr>  
    <!-- <tr>{{form.available|field_as_td_h}}</tr>   --> 
     
<tr><th>{% trans '调动栏位:' %}</th><td><div id="div_id_chk"><table class="tbl_change_type"><tr><td>{{form.chkdept.as_widget}}{{form.chkdept.label_tag}} </td><td>{{form.chktitle.as_widget}} {{form.chktitle.label_tag}} </td><td>{{form.chkhiretype.as_widget}}{{form.chkhiretype.label_tag}} </td><td>{{form.chkarea.as_widget}}{{form.chkarea.label_tag}}</td></tr></table></div></td></tr>
<tr><th></th><td>
<div></div>
<table class="display_table table" width="730px">
<thead>
<tr><th width="120px">{% trans '调动栏位' %}</th><th width="305px">{% trans '调动前' %}</th><th width="305px">{% trans '调动后' %}</th></tr></thead>
<tr class="tr_message"><td colspan="3">{% trans '请选择调动栏位' %}</td></tr>
<tr class="tr_dept tr_postion"><td>{% trans '部门' %}</td><td>{{form.olddept.as_widget}}</td><td>{{form.newdept.as_widget}}</td></tr>
<tr class="tr_title tr_postion"><td>{% trans '职务' %}</td><td>{{form.oldtitle.as_widget}}</td><td>{{form.newtitle.as_widget}}</td></tr>
<tr class="tr_hiretype tr_postion"><td>{% trans '雇用类型' %}</td><td>{{form.oldhiretype.as_widget}}</td><td>{{form.newhiretype.as_widget}}</td></tr>
<tr class="tr_area tr_postion"><td>{% trans '区域' %}</td><td>{{form.oldarea.as_widget}}</td><td>{{form.newarea.as_widget}}</td></tr>

</table></td></tr></table></div>
<div class="displayN"><table><tr>{{form.changepostion|field_as_td_h}}{{form.oldvalue|field_as_td_h}}{{form.newvalue|field_as_td_h}}</tr></table></div>
</div></td></tr>

{% endautoescape %}
{% endblock %}