zkeco-core/adms/mysite/att/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls.defaults import *
import models
from mysite.personnel.models.empwidget import get_widget_for_select_emp
import views
from mysite.att.models.nomodelview import getData
from mysite.att.models.schclass import getSchClass

from models import nomodelview

urlpatterns=patterns('mysite.att',
(r'^getallexcept/$',views.funGetAllExcept),
(r'^tmpshifts/$',views.funTmpShifts),
(r'^FetchSchPlan/$',views.funFetchSchPlan),
(r'^assignedShifts/$',views.funAssignedShifts),
(r'^deleteEmployeeShift/$',views.funDeleteEmployeeShift),
(r'^worktimezone/$',views.funWorkTimeZone),
(r'^getshifts/$',views.funGetShifts),
(r'^attrule/$',views.funAttrule),
(r'^shift_detail/$',views.funShift_detail),
(r'^deleteShiftTime/$',views.funDeleteShiftTime),
(r'^deleteAllShiftTime/$',views.funDeleteAllShiftTime),
(r'^addShiftTimeTable/$',views.funAddShiftTimeTable),

(r'^getschclass/$',views.funGetSchclass),
(r'^AttCalculate/$',views.funAttCalculate),
(r'^AttReCalc/$',views.funAttReCalculate),
(r'^AttParamSetting/$',views.funAttParamSetting),
(r'^SaveAttParamSetting/$',views.SaveAttParamSetting),
(r'^Forget/$',views.funForget),
(r'^AttUserOfRun/$',views.funAttUerOfRun),
(r'^SaveForget/$',views.SaveForget),
(r'^newgetSchClass/$',getSchClass),
(r'^choice_widget_for_select_emp/$',get_widget_for_select_emp),
(r'^getmodeldata/(?P<app_lable>[^/]*)/(?P<model_name>[^/]*)/$',views.funGetModelData),
(r'^getData/$', getData),   #-----------------------------------------
(r'^DeviceUserManage/$',views.funAttDeviceUserManage),
(r'^DeviceDataManage/$',views.funAttDeviceDataManage),
(r'^DailyCalcReport/$', views.fundailycalcReport),
(r'^CalcReport/$', views.funCalcReport),    #---考勤汇总表
(r'^att_abnormal_report/$', nomodelview.att_abnormal_report),    #---考勤异常表
(r'^CalcLeaveReport/$', views.funCalcLeaveReport),
(r'^GenerateEmpPunchCard/$', views.GenerateEmpPunchCard),
(r'^lereport/$', views.funLEReport),
)



zkeco-core/adms/mysite/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls.defaults import *
from django.contrib.auth.views import login, logout, password_change
from settings import MEDIA_ROOT,ADDITION_FILE_ROOT,LOGIN_REDIRECT_URL,UNIT_URL
from django.template import loader, Context, RequestContext
from django.http import QueryDict, HttpResponse, HttpResponseRedirect, HttpResponseNotModified
from django.shortcuts import render_to_response
from dbapp.utils import *
from staticfiles import serve
import base
from base.log import logger
from django.core.urlresolvers import RegexURLPattern
from django.utils.translation import ugettext_lazy as _

from core.site_views import index,my_i18n,checkno

surl=UNIT_URL[1:]

def tmp_url():
    return surl+'tmp/'

urlpatterns = patterns('',
    (r'^'+surl+'api/', include('mysite.api.urls')),         #----RESTful API 接口 指向 api 目录  python-support/piston 相关 在urls最上层
    ('i18n/setlang/', my_i18n), #系统语言设置
# 几个静态文件请求
    (r'^'+surl+'file/(?P<path>.*)$', serve, {'document_root': ADDITION_FILE_ROOT, 'show_indexes': True}),
    (r'^'+tmp_url()+'(?P<path>.*)$', serve, {'document_root': tmpDir(), 'show_indexes': True}),
    (r'^'+surl+'media/(?P<path>.*)$', serve, {'document_root': MEDIA_ROOT, 'show_indexes': False}),
    (r'^media/(?P<path>.*)$', serve,  {'document_root': MEDIA_ROOT, 'show_indexes': True}),
    
    (r'^'+surl+'checkno/(?P<app_label>[^/]*)/(?P<model_name>[^/]*)/$',checkno),
    
    (r'^'+surl+'accounts/', include('mysite.authurls')),         #用户登录、登出、密码设置
    
    (r'^'+surl+'data/', include('dbapp.urls')),                         #通用数据管理
    (r'^'+surl+'iclock/', include('mysite.iclock.urls')),         #adms管理    
    (r'^'+surl+'testapp/', include('mysite.testapp.urls')),         #用于测试的应用
    (r'^'+surl+'personnel/',include('mysite.personnel.urls')),   #人事管理系统
    (r'^'+surl+'worktable/',include('mysite.worktable.urls')),   #我的工作面板
    (r'^$', index),
)

dict_urls={
    "mysite.att":url(r'^'+surl+'att/',include('mysite.att.urls'),prefix=''),#考勤系统系理
    "mysite.iaccess":url(r'^'+surl+'iaccess/',include('mysite.iaccess.urls'),prefix=''),#zkaccess门禁系统管理
    "mysite.video":url(r'^'+surl+'video/',include('mysite.video.urls'),prefix=''),#视频系统管理
    "rosetta":url(r'^rosetta/', include('rosetta.urls'),prefix='')
}

for k,v in dict_urls.items():
    if k in settings.INSTALLED_APPS:
        urlpatterns.append(v)

zkeco-core/adms/mysite/att/models/attcalclog.py
# -*- coding: utf-8 -*-
from django.db import models, connection
from django.db.models import Q
from django.contrib.auth.models import User, Permission, Group
import datetime
import os
import string
from django.contrib import auth
from django.conf import settings
from django.core.exceptions import ObjectDoesNotExist
from django.core.cache import cache
from dbapp.utils import *
from django.utils.translation import ugettext_lazy as _
from django.contrib.contenttypes.models import ContentType
from django.forms.models import ModelChoiceIterator

from base.cached_model import CachingModel
from base.operation import Operation


class attCalcLog(models.Model):
    DeptID=models.IntegerField(db_column='DeptID',null=True,blank=True, default=0)
    UserID = models.IntegerField(db_column='UserId', blank=True)
    StartDate = models.DateTimeField( db_column='StartDate',blank=True,null=True)
    EndDate = models.DateTimeField(db_column='EndDate',blank=True)
    OperTime = models.DateTimeField(db_column='OperTime',blank=True)
    Type=models.IntegerField(null=True,default=0,blank=True, editable=False)
    class Admin(CachingModel.Admin):
        visible=False
    class Meta:
        app_label='att'
        db_table = 'attcalclog'

zkeco-core/adms/mysite/att/models/attexception.py
# -*- coding: utf-8 -*-
from django.db import models, connection
from django.db.models import Q
from django.contrib.auth.models import User, Permission, Group
from base.models import CachingModel
import datetime
import os
import string
from django.contrib import auth
from django.conf import settings
from django.core.exceptions import ObjectDoesNotExist
from django.core.cache import cache
from dbapp.utils import *
from django.utils.translation import ugettext_lazy as _
from django.contrib.contenttypes.models import ContentType
from django.forms.models import ModelChoiceIterator
from mysite.personnel.models import Employee, EmpForeignKey
from base.models import CachingModel, Operation

class AttException(CachingModel):
        '''
        请假明细表模型（异常记录表）【统计结果】
        '''
        UserID = EmpForeignKey(verbose_name=_(u'人员'),db_column='UserId',  blank=False, null=False)
        StartTime = models.DateTimeField(_(u'开始时间'), db_column='StartTime')
        EndTime = models.DateTimeField(_(u'结束时间'), db_column='EndTime')
        ExceptionID=models.IntegerField(_(u'请假类型'),null=True,blank=True,default=0)
        AuditExcID=models.IntegerField(_(u'审核状态'),null=True,blank=True,default=0)
        OldAuditExcID=models.IntegerField(_(u'前次审核状态'),null=True,blank=True,default=0)
        OverlapTime=models.IntegerField(_(u'排班时长'),db_column='OverlapTime',null=True,blank=True,default=0)               
        TimeLong=models.IntegerField(_(u'总时长（分钟）'), db_column='TimeLong',null=True,blank=True,default=0)                  
        InScopeTime=models.IntegerField(_(u'有效时长（分钟）'), db_column='InScopeTime',null=True,blank=True,default=0)  
        AttDate=models.DateTimeField(_(u'日期'),db_column='AttDate',null=True,blank=True)
        OverlapWorkDayTail=models.IntegerField( db_column='OverlapWorkDayTail')
        OverlapWorkDay=models.FloatField(_(u'排班工作日'),db_column='OverlapWorkDay',null=True,default=1,blank=True)      
        schindex=models.IntegerField(db_column='schindex',null=True,blank=True,default=0)
        Minsworkday=models.IntegerField(db_column='Minsworkday',null=True,blank=True,default=0)
        Minsworkday1=models.IntegerField(db_column='Minsworkday1',null=True,blank=True,default=0)
        schid=models.IntegerField(db_column='schid',null=True,blank=True,default=0)

        class Admin(CachingModel.Admin):
                default_give_perms=["contenttypes.can_AttCalculate",]
                visible=False
                list_display=('UserID_id','UserID.PIN','UserID.EName','UserID.DeptID','StartTime','EndTime','ExceptionID|AttExceptDesc','InScopeTime')
        class Meta:
                app_label='att'
                db_table='attexception'
                unique_together = (("UserID","AttDate", "StartTime"),)

zkeco-core/adms/mysite/att/models/attrecabnormite.py
# -*- coding: utf-8 -*-
from django.db import models, connection
from django.db.models import Q
from django.contrib.auth.models import User, Permission, Group
import datetime
import os
import string
from django.contrib import auth
from django.conf import settings
from django.core.exceptions import ObjectDoesNotExist
from django.core.cache import cache
from dbapp.utils import *
from django.utils.translation import ugettext_lazy as _
from django.contrib.contenttypes.models import ContentType
from django.forms.models import ModelChoiceIterator
from mysite.personnel.models import Employee, EmpForeignKey
from mysite.iclock.models.model_trans import ATTSTATES

#统计结果详情
class attRecAbnormite(models.Model):
    UserID = EmpForeignKey(verbose_name=_(u'人员'),db_column='userid')
    checktime = models.DateTimeField(_(u'考勤时间'), db_column='checktime')
    CheckType = models.CharField(_(u'考勤状态'),db_column='CheckType', max_length=5,choices=ATTSTATES)
    NewType = models.CharField(_(u'更正状态'), db_column='NewType', max_length=2,null=True,blank=True,choices=ATTSTATES)
    AbNormiteID=models.IntegerField(db_column='AbNormiteID',  null=True,blank=True)
    SchID=models.IntegerField(_(u'时段'),db_column='SchID',  null=True,blank=True)
    OP=models.IntegerField(_(u'操作'),db_column='OP',  null=True,blank=True)
    AttDate=models.DateTimeField(_(u'日期'),db_column='AttDate',null=True,blank=True)

    def __unicode__(self):
        return unicode(u"%s"%(self.UserID))
    
    class Admin:
        default_give_perms=["contenttypes.can_AttCalculate"]
        app_menu="att_set"
        api_fields=('UserID.PIN','UserID.EName','checktime','CheckType','NewType')
        list_display=('UserID_id','UserID.PIN','UserID.EName','checktime','CheckType','NewType')
        visible=False
    class Meta:
        app_label='att'
        verbose_name=_(u"统计结果详情")
        db_table='attrecabnormite'
        unique_together = (("UserID","AttDate", "checktime"),)

zkeco-core/adms/mysite/att/models/model_empspecday.py
# -*- coding: utf-8 -*-
from django.db import models, connection
from django.db.models import Q
import datetime
import os
import string
from django.contrib import auth
from django.conf import settings
from django.core.exceptions import ObjectDoesNotExist
from django.core.cache import cache
from dbapp.utils import *
from django.utils.translation import ugettext_lazy as _
from django.contrib.contenttypes.models import ContentType
from django.forms.models import ModelChoiceIterator
from base.models import CachingModel, Operation
from model_leaveclass import LeaveClass
from django.db.models import Q
from mysite.personnel.models.model_emp import Employee,EmpForeignKey,EmpMultForeignKey,EmpPoPForeignKey
from mysite.personnel.models.empwidget import ZMulPopEmpChoiceWidget
from base.operation import ModelOperation

AUDIT_STATES=(
    (0,_(u'申请')),
    (1,_(u'正在审核')),
    (2,_(u'已接受')),
    (3,_(u'拒绝')),
    (4,_(u'暂停')),
    (5,_(u'重申请')),
    (6,_(u'重新申请')),
    (7,_(u'取消请假'))
)


#员工请假(考勤例外)表##
class EmpSpecDay(CachingModel):
    '''
    请假原始表模型
    '''
    emp=EmpPoPForeignKey(verbose_name=_(u'人员'),db_column='UserID', null=False, blank=False)
    start= models.DateTimeField(_(u'开始时间'), db_column='StartSpecDay', null=False, default=nextDay(), blank=False)
    end = models.DateTimeField(_(u'结束时间'), db_column='EndSpecDay', null=True, default=endOfDay(nextDay()),blank=False)
    leaveclass=models.ForeignKey(LeaveClass, verbose_name=_(u'假类'), db_column='DateID', null=False, blank=False,default=1)
    reson=models.CharField(_(u'请假原因'), db_column='YUANYING', max_length=100,null=True,blank=True)
    apply=models.DateTimeField(_(u'填写时间'), db_column='Date', null=True, default=datetime.datetime.now(), blank=True)
    state=models.CharField(_(u'申请状态'),max_length=2, null=True, db_column="State", default=2, blank=True, choices=AUDIT_STATES, editable=False)
    def save(self, *args, **kwargs):
        if self.start>=self.end:
            raise Exception(_(u'结束时间不能小于开始时间'))
        
        tt=EmpSpecDay.objects.filter(emp=self.emp,start__lte=self.end,end__gte=self.start)
        if tt and tt[0].id !=self.id:
            raise Exception(_(u'请假时间重复'))
#        tmp=EmpSpecDay.objects.filter(Q(emp=self.emp,start__lte=self.start,end__gte=self.end)| Q(emp=self.emp,start__gte=self.start,end__lte=self.end)).exclude(pk=1)
#        if tmp and tmp[0].pk !=self.pk :
#            raise Exception(_(u'已存在相同请假记录！'))
        
        super(EmpSpecDay,self).save()
        from mysite.att.models.__init__ import get_autocalculate_time as gct
        from model_waitforprocessdata import WaitForProcessData as wfpd
        import datetime
        gct_time=gct()
        if self.start<gct_time or self.end<=gct_time:
            wtmp=wfpd()                
            st=self.start
            et=self.end
            wtmp.UserID=self.emp
            wtmp.starttime=st
            wtmp.endtime=et
            #wtmp.customer=self.customer
            wtmp.save()
        
    def __unicode__(self):
        return u"%s: %s, %s"%(self.emp, self.start and self.start.strftime("%m-%d") or "", self.leaveclass)
        #return u"%s: %s, %s"%(self.emp, self.start and self.start.strftime("%m-%d") or "", self.leaveclass)出错
    class _add(ModelOperation):
        visible=False
        help_text=_(u"新增记录") #新增记录
        verbose_name=_(u"新增")
        def action(self):
            pass
    class OpAddManyUserID(ModelOperation):
        help_text=_(u'''新增''')
        verbose_name=_(u"新增请假")
        params=(
            ('UserID', EmpMultForeignKey(verbose_name=_(u'人员'),blank=False,null=False)),          
            ('start',models.DateTimeField(_(u'开始时间'))),
            ('end',models.DateTimeField(_(u'结束时间'))),
            ('leaveclass',models.ForeignKey(LeaveClass, verbose_name=_(u'假类'))),
            ('reson',models.CharField(_(u'请假原因'),blank=True,null=True,max_length=100)),
            ('apply',models.DateTimeField(_(u'填写时间'), default=datetime.datetime.now(), blank=True)),
        )
        def action(self, **args):
            emps=args.pop('UserID')
            if self.request:
                   if not emps:
                       depts=self.request.POST.getlist('deptIDs')
                       emps=Employee.objects.filter(DeptID__in=depts)
            if args['start']>=args['end']:
                raise Exception(_(u'结束时间不能小于开始时间'))
            if not emps:
                raise Exception(_(u'请选择人员'))
            
            for emp in emps: 
                EmpSpecDay(emp=emp, **args).save()

    class Admin(CachingModel.Admin):
        from mysite.personnel.models.empwidget import ZMulPopEmpChoiceWidget
        sort_fields=["emp.PIN","start","end"]
        disabled_perms=['add_empspecday','dataimport_empspecday']
        #default_widgets={"emp":ZMulPopEmpChoiceWidget}
        list_filter =['emp','reson','state','leaveclass']
        query_fields=['emp__PIN','emp__EName','reson','state']
        list_display=['emp.PIN','emp.EName','start','end','reson','leaveclass']
        
        menu_index=1
    class Meta:
        app_label='att'
        db_table = 'user_speday'
        verbose_name = _(u'请假')
        verbose_name_plural=verbose_name
        unique_together = (("emp", "start","leaveclass"),)


zkeco-core/adms/mysite/att/models/model_waitforprocessdata.py
# -*- coding: utf-8 -*-
from django.db import models, connection


from django.utils.translation import ugettext_lazy as _
from django.contrib.contenttypes.models import ContentType
from django.forms.models import ModelChoiceIterator
from mysite.personnel.models.model_emp import Employee,EmpForeignKey,EmpMultForeignKey,EmpPoPForeignKey,EmpPoPMultForeignKey

from base.cached_model import CachingModel
from base.operation import Operation,ModelOperation

#from mysite.sitebackend.models import Customer

PROCESSFLAG=(
    (1,_(u'未处理')),
    (2,_(u'处理完成')),
    (3,_(u'处理失败')),
)
class WaitForProcessData(CachingModel):
    UserID=EmpForeignKey(verbose_name=_(u'人员'))
    starttime=models.DateTimeField(_(u'开始时间'),null=False,blank=False)
    endtime=models.DateTimeField(_(u'结束时间'),null=False,blank=False)
    flag=models.IntegerField(_(u'处理标志'),null=False,blank=False,default=1,choices=PROCESSFLAG)    
    
    class Admin(CachingModel.Admin):
        visible=True
        verbose_name=_(u'后台计算命令队列')
    class Meta:
        app_label="att"

zkeco-core/adms/mysite/att/templates/ForgetAtt_list.html
{% extends "data_list.html" %}
{% load i18n %}
{% block getdatalist %}
{% endblock %}
{% block content %}
<div id="content" ></div>
{% endblock %}
{% block op_for_tab %}
{% endblock %}


{% block addjs %}
function getOptions()
{
	options_html=""
	for(var i=0;i<states.length;i++)
		options_html+="<option value='"+i+"'>"+states[i]+"</option>"
	return options_html;
}
$(function(){
EmpAndDept={{ForgetAtt_list}};
states=EmpAndDept.states;
var selectEmpoloyee=""

$("#content").html(""
+"<div class='form_help'>"
		+"<span class='icon_Shift_Detail'>&nbsp;</span>{%trans ' 当某一部分或者全体员工因故未签到、签退，可使用本功能给员工添加签到、签退记录，其修改情况可在出勤记录查询功能中查询' %}"
		+"<br />{% trans '单击部门不选人员则按整个部门及其下属部门进行集体补记录，否则按所选人员进行补记录' %}</div>"
+"<div class='module' style='position:relative;margin:10px;'>"
+"<table style='margin-bottom: 2px;'><tr>"
	+"<th style='vertical-align:top;text-align:right;width:55px;'><label class='required'>{% trans '人员:'%} </label></th>"
	+"<td style='vertical-align:top;'><div id='show_dept_emp_tree' style='min-height: 200px;'></div></td></tr>"
	+"<tr><td colspan='2' style='vertical-align:top;width:40%;'><div id='id_conditions'>"
		+"<form id='id_edit_form' method='POST'><table id='id_setField'>"

+"<tr><th><label for='id_checktype' class='required'>{% trans '补签方式:'%}</label></th>"
		+"<td><select style='width:120px !important;' id='id_checktype' name='checktype'>"+getOptions()+"</select></td><tr>"

		+"<tr><th><label for='id_checkdate' class='required'>{% trans '日期:'%}</label></th>"
		+"<td><input type='none' id='id_checkdate' name='checkdate' value='' size='11' maxlength='10' class='vDateOnlyField'/></td></tr>"

		+"<tr><th><label for='id_checktime' class='required'>{% trans '时间:'%}</label></th>"
		+"<td><input type='none' id='id_checktime' name='checktime' value='' size='9' maxlength='8' class='vTimeField'/></td></tr>"
		
		+"<tr><th><label for='id_reson'>{% trans '原因:'%}</label></th>"
		+"<td><input style='width:120px !important;' type='text' id='id_reson' name='reson' value='' /></td></tr>"
		+"<input type='hidden' id='id_hidden_emp' value='' name='UserIDs' />"
        +"<input type='hidden' id='id_hidden_depts' value='' name='deptIDs' />"
		+"<tr><th> </th><td></td></tr>"
		+"<tr><th></th><td><span class='action_SaveandContinue'></span><a id='id_submit'class='Link_blue1' href='javascript:void(0)' >{%trans "提交" %}</a>&nbsp;&nbsp;&nbsp;&nbsp;<span class='action_Cancel'></span><a class='Link_blue1' onclick='window.history.back(); return false;' href='javascript:void(0)'>{%trans "返回" %}</a></td></tr>"
		+"<tr><th> </th><td></td></tr>"			
		+"<tr><td colspan='2'><span id='id_error'></span></td></tr>"
	+"</table></form></div></td>"
+"</tr></table></div>"
);
$.ajax({
	url:"../../att/choice_widget_for_select_emp/?multiple=true",
	type:"POST",
	dataType:"html",
	success:function(sdata){
		//alert($("#show_dept_emp_tree"));
		$("#show_dept_emp_tree").html(sdata);
		
	}
});
//递交
$("#id_submit").click(function(){
	var usr_ids=[]
	$("#show_dept_emp_tree").find(".zd_Emp>div:last .div_store_emp input").each(function(index,elem){
		usr_ids[index]=$(this).val();
	});
	if(usr_ids.length==0){
		alert("you should  select one person at least!");
		return;
	}
	$("#id_hidden_emp").val(usr_ids.join(","));
	var opt={
		url:"../../att/SaveForget/",
		dataType:"text",
		type:"POST",
		success:function(retdata){
			if(retdata.indexOf("result=0")==0){
					$("#id_error").css("display","block");
					$("#id_error").html("<ul class='errorlist'><li>{%trans '保存成功,如需查看，请浏览<统计与报表-->签卡记录表>'%}</li></ul>");				
				}
			else
				{
					$("#id_error").css("display","block");
					var i=retdata.indexOf("message=\"");
					var message=retdata.substr(i+18)
			
					//$("#id_error").html("<ul class='errorlist'><li>{%trans '保存失败!'%}</li></ul>");
					$("#id_error").html("<ul class='errorlist'><li>"+message+"</li></ul>");
				}
		}
	}
	$("#id_edit_form").ajaxSubmit(opt);
});

var currDate=new Date();
$("#id_checkdate").val(currDate.getFullYear()
						+"-"
						+(currDate.getMonth()+1<10?"0"+(currDate.getMonth()+1):currDate.getMonth()+1)
						+"-"
						+currDate.getDate()
						);
$("#id_checktime").val(currDate.toLocaleTimeString());

});
{% endblock %}

<style>
form th {
text-align:left;
padding-top:4px;
vertical-align: top;
}
#id_setField th{text-align:right;}
.form_help {background-color: #ccddee; padding: 10px; margin:10px;}
</style>







zkeco-core/adms/mysite/att/templates/NUM_RUN_opform_OpAddTimeTable.html
{% extends "data_opform.html" %}
{% load i18n %}
{% block addjs %}
var selectcount=0
function before_submit()
{
	var hascheck=false	
	$(".div_time_select").find("input[type='checkbox']").each(function(){
		if($(this).attr("checked"))
		{
			hascheck=true;
			return false;
		}
	});
	if(!hascheck)
	{
		alert(gettext("请选择时段"));
		return false;
	}
	
	
	var hastt=false
	$("input[name='days']").each(function(){
		if($(this).attr("checked"))
		{
			hastt=true;
			return false;
		}
	});
	if(!hastt)
	{
		alert(gettext("选择日期"));
		return false;
	}
	return true
	
}

$(function(){

    $.ajax({
    
    	    url:"{{request.surl}}../../../att/getmodeldata/att/SchClass/?fields=SchclassID,SchName,StartTime,EndTime",
    	    type:"POST",
    	    dataType:"json",
    	    success:function(sdata){
    	       var html="";
               for(var i =0;i<sdata.length;i++)
               {
               		var data=sdata[i];
               		html+="<ul>";
                    html+="<li><input class='appen_schclass' type='checkbox' name='time_table' value='"+ data[0]+"' />";
                    html+=" "+ data[1] +"("+ data[2] +"--"+ data[3] +")</li>";
                    html+="</ul>";
               };
    	        $("#id_add_time_table").append(html);
    	    }    
		});
     $("#id_selectcount").html("("+gettext("已选择")+selectcount+")");
    $("#id_chk_selectall").click(function(){
        var bln=$(this).attr("checked");
        $(".div_chk_date").find("input[type='checkbox']").each(function(){
            $(this).attr("checked",bln);
        });
        if (bln)
        {
            selectcount=$(".div_chk_date").find("input[type='checkbox']").length
            
        }
        else
        {
            selectcount=0
        }
        $("#id_selectcount").html("("+gettext("已选择")+selectcount+")");
    })
    $(".div_chk_date").find("input[type='checkbox']").click(function(){
                var t=$(this).attr("checked");
               
                if(t)
                {selectcount=selectcount+1}
                else
                { if (selectcount>0)
                    selectcount=selectcount-1
                }
                
                
                $("#id_selectcount").html("("+gettext("已选择")+selectcount+")");
            });
    
});
{% endblock %}
{% block form %}
{% autoescape off %}
<tr>
<td style="vertical-align: top;">
  <div class="div_cls_opaddtable">
  <table class="id_tbl_opaddtable">
  <tr><td colspan="2"><div style="height:25px;line-height:25px;">{% trans '请选择时段:' %}</div><div id ="id_add_time_table" class="div_time_select"></div></td></tr>
  <tr class="displayN"><th style="line-height:21px;">{% trans '是否需要加班' %}<td>{{ form.if_overtime.as_widget }}</td></tr>
  <tr class="displayN"><th style="line-height:21px;">{% trans '加班时间(分钟)' %}<td>{{ form.overtime.as_widget }}</td></tr>

  {% for i,k in form.errors.items %}
  {{i}}{{k}}
  {% endfor %}

  </table>
  
</div>
</td>
  <td id="id_opaddtable_chk_date"><div style="height:26px;line-height:26px;">{% trans '选择日期:' %} <span> <input type="checkbox" id="id_chk_selectall" \> <span id="id_selectcount"></span></span></div><div class="div_chk_date">{{ form.days.as_widget }}</div></td>
</tr>




{% endautoescape %}
{% endblock %}

